package client.demo.dao;

import client.demo.model.Weather;
import client.demo.model.WeatherExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeatherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int countByExample(WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int deleteByExample(WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int insert(Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int insertSelective(Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    List<Weather> selectByExample(WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    Weather selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") Weather record, @Param("example") WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int updateByExample(@Param("record") Weather record, @Param("example") WeatherExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int updateByPrimaryKeySelective(Weather record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int updateByPrimaryKey(Weather record);
}