package client.demo.dao;

import client.demo.model.WeatherBack;
import client.demo.model.WeatherBackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WeatherBackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int countByExample(WeatherBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int deleteByExample(WeatherBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int insert(WeatherBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int insertSelective(WeatherBack record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    List<WeatherBack> selectByExample(WeatherBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") WeatherBack record, @Param("example") WeatherBackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    int updateByExample(@Param("record") WeatherBack record, @Param("example") WeatherBackExample example);
}