package client.demo.model;

import java.util.ArrayList;
import java.util.List;

public class WeatherBackExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    public WeatherBackExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCountyIsNull() {
            addCriterion("county is null");
            return (Criteria) this;
        }

        public Criteria andCountyIsNotNull() {
            addCriterion("county is not null");
            return (Criteria) this;
        }

        public Criteria andCountyEqualTo(String value) {
            addCriterion("county =", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotEqualTo(String value) {
            addCriterion("county <>", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyGreaterThan(String value) {
            addCriterion("county >", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyGreaterThanOrEqualTo(String value) {
            addCriterion("county >=", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLessThan(String value) {
            addCriterion("county <", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLessThanOrEqualTo(String value) {
            addCriterion("county <=", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyLike(String value) {
            addCriterion("county like", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotLike(String value) {
            addCriterion("county not like", value, "county");
            return (Criteria) this;
        }

        public Criteria andCountyIn(List<String> values) {
            addCriterion("county in", values, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotIn(List<String> values) {
            addCriterion("county not in", values, "county");
            return (Criteria) this;
        }

        public Criteria andCountyBetween(String value1, String value2) {
            addCriterion("county between", value1, value2, "county");
            return (Criteria) this;
        }

        public Criteria andCountyNotBetween(String value1, String value2) {
            addCriterion("county not between", value1, value2, "county");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureIsNull() {
            addCriterion("max_temperature is null");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureIsNotNull() {
            addCriterion("max_temperature is not null");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureEqualTo(String value) {
            addCriterion("max_temperature =", value, "maxTemperature");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureNotEqualTo(String value) {
            addCriterion("max_temperature <>", value, "maxTemperature");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureGreaterThan(String value) {
            addCriterion("max_temperature >", value, "maxTemperature");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureGreaterThanOrEqualTo(String value) {
            addCriterion("max_temperature >=", value, "maxTemperature");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureLessThan(String value) {
            addCriterion("max_temperature <", value, "maxTemperature");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureLessThanOrEqualTo(String value) {
            addCriterion("max_temperature <=", value, "maxTemperature");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureLike(String value) {
            addCriterion("max_temperature like", value, "maxTemperature");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureNotLike(String value) {
            addCriterion("max_temperature not like", value, "maxTemperature");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureIn(List<String> values) {
            addCriterion("max_temperature in", values, "maxTemperature");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureNotIn(List<String> values) {
            addCriterion("max_temperature not in", values, "maxTemperature");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureBetween(String value1, String value2) {
            addCriterion("max_temperature between", value1, value2, "maxTemperature");
            return (Criteria) this;
        }

        public Criteria andMaxTemperatureNotBetween(String value1, String value2) {
            addCriterion("max_temperature not between", value1, value2, "maxTemperature");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherIsNull() {
            addCriterion("max_weather is null");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherIsNotNull() {
            addCriterion("max_weather is not null");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherEqualTo(String value) {
            addCriterion("max_weather =", value, "maxWeather");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherNotEqualTo(String value) {
            addCriterion("max_weather <>", value, "maxWeather");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherGreaterThan(String value) {
            addCriterion("max_weather >", value, "maxWeather");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherGreaterThanOrEqualTo(String value) {
            addCriterion("max_weather >=", value, "maxWeather");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherLessThan(String value) {
            addCriterion("max_weather <", value, "maxWeather");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherLessThanOrEqualTo(String value) {
            addCriterion("max_weather <=", value, "maxWeather");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherLike(String value) {
            addCriterion("max_weather like", value, "maxWeather");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherNotLike(String value) {
            addCriterion("max_weather not like", value, "maxWeather");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherIn(List<String> values) {
            addCriterion("max_weather in", values, "maxWeather");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherNotIn(List<String> values) {
            addCriterion("max_weather not in", values, "maxWeather");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherBetween(String value1, String value2) {
            addCriterion("max_weather between", value1, value2, "maxWeather");
            return (Criteria) this;
        }

        public Criteria andMaxWeatherNotBetween(String value1, String value2) {
            addCriterion("max_weather not between", value1, value2, "maxWeather");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionIsNull() {
            addCriterion("max_wind_direction is null");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionIsNotNull() {
            addCriterion("max_wind_direction is not null");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionEqualTo(String value) {
            addCriterion("max_wind_direction =", value, "maxWindDirection");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionNotEqualTo(String value) {
            addCriterion("max_wind_direction <>", value, "maxWindDirection");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionGreaterThan(String value) {
            addCriterion("max_wind_direction >", value, "maxWindDirection");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("max_wind_direction >=", value, "maxWindDirection");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionLessThan(String value) {
            addCriterion("max_wind_direction <", value, "maxWindDirection");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionLessThanOrEqualTo(String value) {
            addCriterion("max_wind_direction <=", value, "maxWindDirection");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionLike(String value) {
            addCriterion("max_wind_direction like", value, "maxWindDirection");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionNotLike(String value) {
            addCriterion("max_wind_direction not like", value, "maxWindDirection");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionIn(List<String> values) {
            addCriterion("max_wind_direction in", values, "maxWindDirection");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionNotIn(List<String> values) {
            addCriterion("max_wind_direction not in", values, "maxWindDirection");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionBetween(String value1, String value2) {
            addCriterion("max_wind_direction between", value1, value2, "maxWindDirection");
            return (Criteria) this;
        }

        public Criteria andMaxWindDirectionNotBetween(String value1, String value2) {
            addCriterion("max_wind_direction not between", value1, value2, "maxWindDirection");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerIsNull() {
            addCriterion("max_wind_power is null");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerIsNotNull() {
            addCriterion("max_wind_power is not null");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerEqualTo(String value) {
            addCriterion("max_wind_power =", value, "maxWindPower");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerNotEqualTo(String value) {
            addCriterion("max_wind_power <>", value, "maxWindPower");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerGreaterThan(String value) {
            addCriterion("max_wind_power >", value, "maxWindPower");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerGreaterThanOrEqualTo(String value) {
            addCriterion("max_wind_power >=", value, "maxWindPower");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerLessThan(String value) {
            addCriterion("max_wind_power <", value, "maxWindPower");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerLessThanOrEqualTo(String value) {
            addCriterion("max_wind_power <=", value, "maxWindPower");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerLike(String value) {
            addCriterion("max_wind_power like", value, "maxWindPower");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerNotLike(String value) {
            addCriterion("max_wind_power not like", value, "maxWindPower");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerIn(List<String> values) {
            addCriterion("max_wind_power in", values, "maxWindPower");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerNotIn(List<String> values) {
            addCriterion("max_wind_power not in", values, "maxWindPower");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerBetween(String value1, String value2) {
            addCriterion("max_wind_power between", value1, value2, "maxWindPower");
            return (Criteria) this;
        }

        public Criteria andMaxWindPowerNotBetween(String value1, String value2) {
            addCriterion("max_wind_power not between", value1, value2, "maxWindPower");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureIsNull() {
            addCriterion("min_temperature is null");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureIsNotNull() {
            addCriterion("min_temperature is not null");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureEqualTo(String value) {
            addCriterion("min_temperature =", value, "minTemperature");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureNotEqualTo(String value) {
            addCriterion("min_temperature <>", value, "minTemperature");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureGreaterThan(String value) {
            addCriterion("min_temperature >", value, "minTemperature");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureGreaterThanOrEqualTo(String value) {
            addCriterion("min_temperature >=", value, "minTemperature");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureLessThan(String value) {
            addCriterion("min_temperature <", value, "minTemperature");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureLessThanOrEqualTo(String value) {
            addCriterion("min_temperature <=", value, "minTemperature");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureLike(String value) {
            addCriterion("min_temperature like", value, "minTemperature");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureNotLike(String value) {
            addCriterion("min_temperature not like", value, "minTemperature");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureIn(List<String> values) {
            addCriterion("min_temperature in", values, "minTemperature");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureNotIn(List<String> values) {
            addCriterion("min_temperature not in", values, "minTemperature");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureBetween(String value1, String value2) {
            addCriterion("min_temperature between", value1, value2, "minTemperature");
            return (Criteria) this;
        }

        public Criteria andMinTemperatureNotBetween(String value1, String value2) {
            addCriterion("min_temperature not between", value1, value2, "minTemperature");
            return (Criteria) this;
        }

        public Criteria andMinWeatherIsNull() {
            addCriterion("min_weather is null");
            return (Criteria) this;
        }

        public Criteria andMinWeatherIsNotNull() {
            addCriterion("min_weather is not null");
            return (Criteria) this;
        }

        public Criteria andMinWeatherEqualTo(String value) {
            addCriterion("min_weather =", value, "minWeather");
            return (Criteria) this;
        }

        public Criteria andMinWeatherNotEqualTo(String value) {
            addCriterion("min_weather <>", value, "minWeather");
            return (Criteria) this;
        }

        public Criteria andMinWeatherGreaterThan(String value) {
            addCriterion("min_weather >", value, "minWeather");
            return (Criteria) this;
        }

        public Criteria andMinWeatherGreaterThanOrEqualTo(String value) {
            addCriterion("min_weather >=", value, "minWeather");
            return (Criteria) this;
        }

        public Criteria andMinWeatherLessThan(String value) {
            addCriterion("min_weather <", value, "minWeather");
            return (Criteria) this;
        }

        public Criteria andMinWeatherLessThanOrEqualTo(String value) {
            addCriterion("min_weather <=", value, "minWeather");
            return (Criteria) this;
        }

        public Criteria andMinWeatherLike(String value) {
            addCriterion("min_weather like", value, "minWeather");
            return (Criteria) this;
        }

        public Criteria andMinWeatherNotLike(String value) {
            addCriterion("min_weather not like", value, "minWeather");
            return (Criteria) this;
        }

        public Criteria andMinWeatherIn(List<String> values) {
            addCriterion("min_weather in", values, "minWeather");
            return (Criteria) this;
        }

        public Criteria andMinWeatherNotIn(List<String> values) {
            addCriterion("min_weather not in", values, "minWeather");
            return (Criteria) this;
        }

        public Criteria andMinWeatherBetween(String value1, String value2) {
            addCriterion("min_weather between", value1, value2, "minWeather");
            return (Criteria) this;
        }

        public Criteria andMinWeatherNotBetween(String value1, String value2) {
            addCriterion("min_weather not between", value1, value2, "minWeather");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionIsNull() {
            addCriterion("min_wind_direction is null");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionIsNotNull() {
            addCriterion("min_wind_direction is not null");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionEqualTo(String value) {
            addCriterion("min_wind_direction =", value, "minWindDirection");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionNotEqualTo(String value) {
            addCriterion("min_wind_direction <>", value, "minWindDirection");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionGreaterThan(String value) {
            addCriterion("min_wind_direction >", value, "minWindDirection");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionGreaterThanOrEqualTo(String value) {
            addCriterion("min_wind_direction >=", value, "minWindDirection");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionLessThan(String value) {
            addCriterion("min_wind_direction <", value, "minWindDirection");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionLessThanOrEqualTo(String value) {
            addCriterion("min_wind_direction <=", value, "minWindDirection");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionLike(String value) {
            addCriterion("min_wind_direction like", value, "minWindDirection");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionNotLike(String value) {
            addCriterion("min_wind_direction not like", value, "minWindDirection");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionIn(List<String> values) {
            addCriterion("min_wind_direction in", values, "minWindDirection");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionNotIn(List<String> values) {
            addCriterion("min_wind_direction not in", values, "minWindDirection");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionBetween(String value1, String value2) {
            addCriterion("min_wind_direction between", value1, value2, "minWindDirection");
            return (Criteria) this;
        }

        public Criteria andMinWindDirectionNotBetween(String value1, String value2) {
            addCriterion("min_wind_direction not between", value1, value2, "minWindDirection");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerIsNull() {
            addCriterion("min_wind_power is null");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerIsNotNull() {
            addCriterion("min_wind_power is not null");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerEqualTo(String value) {
            addCriterion("min_wind_power =", value, "minWindPower");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerNotEqualTo(String value) {
            addCriterion("min_wind_power <>", value, "minWindPower");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerGreaterThan(String value) {
            addCriterion("min_wind_power >", value, "minWindPower");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerGreaterThanOrEqualTo(String value) {
            addCriterion("min_wind_power >=", value, "minWindPower");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerLessThan(String value) {
            addCriterion("min_wind_power <", value, "minWindPower");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerLessThanOrEqualTo(String value) {
            addCriterion("min_wind_power <=", value, "minWindPower");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerLike(String value) {
            addCriterion("min_wind_power like", value, "minWindPower");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerNotLike(String value) {
            addCriterion("min_wind_power not like", value, "minWindPower");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerIn(List<String> values) {
            addCriterion("min_wind_power in", values, "minWindPower");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerNotIn(List<String> values) {
            addCriterion("min_wind_power not in", values, "minWindPower");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerBetween(String value1, String value2) {
            addCriterion("min_wind_power between", value1, value2, "minWindPower");
            return (Criteria) this;
        }

        public Criteria andMinWindPowerNotBetween(String value1, String value2) {
            addCriterion("min_wind_power not between", value1, value2, "minWindPower");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(String value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(String value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(String value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(String value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(String value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLike(String value) {
            addCriterion("latitude like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotLike(String value) {
            addCriterion("latitude not like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<String> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<String> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(String value1, String value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(String value1, String value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(String value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(String value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(String value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(String value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(String value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLike(String value) {
            addCriterion("longitude like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotLike(String value) {
            addCriterion("longitude not like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<String> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<String> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(String value1, String value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(String value1, String value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(String value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(String value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(String value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(String value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(String value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(String value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLike(String value) {
            addCriterion("time like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotLike(String value) {
            addCriterion("time not like", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<String> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<String> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(String value1, String value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(String value1, String value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_weather_back
     *
     * @mbggenerated do_not_delete_during_merge Tue Oct 26 13:49:44 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_weather_back
     *
     * @mbggenerated Tue Oct 26 13:49:44 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}